### PR TITLE
Updated 404 page

### PR DESCRIPTION
**Pull request by Thunderbottom**

### CODE REVIEW

**Comment by LukeSchlangen** [comment]
I do like the "approach some other page" piece, but I think there is probably a compromise with having some of the other text included to give more context about the site so that people who end up on the site know what they are clicking on. @Thunderbottom, would you consider adding back some of the context from the current 404.html and updating the PR?

**Comment by Thunderbottom** [comment]
I think only an introduction to the site should be fine. Too many lines on the 404 page would make it look quite presumptuous tbh. Let me know if I should go ahead with adding a couple of lines, or if you want I could include all of it.

**Comment by Thunderbottom** [comment]
Also I could help you with redesigning and simplifying the site in some days if you want help with that. As is #28 is a quite good suggestion I suppose.

**Comment by LukeSchlangen** [comment]
Definitely! I think one or two sentences and not everything on the list is perfect. I think #28 is good too, just want to be more specific before asking someone to spend a lot of time on it.

**Comment by Thunderbottom** [comment]
Added a few lines to the html

**Comment by LukeSchlangen** [comment]
Perfect! Thank you so much for all the effort you put into this!

**Comment by Thunderbottom** [comment]
I'll help you with the redesign in a few days as soon as I get some free time off my school work. :)

**Pull request merged**
