### PR TITLE
Resolve #4 - Render Blocking CSS

### LINKED ISSUE #4: Eliminate render-blocking JavaScript and CSS in above-the-fold content
From google page speed test: https://developers.google.com/speed/pagespeed/insights/?url=approachable.io&tab=mobile

> Eliminate render-blocking JavaScript and CSS in above-the-fold content
Your page has 1 blocking CSS resources. This causes a delay in rendering your page.
None of the above-the-fold content on your page could be rendered without waiting for the following resources to load. Try to defer or asynchronously load blocking resources, or inline the critical portions of those resources directly in the HTML.
Optimize CSS Delivery of the following:
http://www.approachable.io/styles.css

This can likely be resolved by moving the `styles.css` tag out of the `<head></head>` tag and into the bottom of the `<body></body>` tag.

Additional suggestions can be found here:
https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery

### PR DESCRIPTION
**Pull request by codyogden**
Move link to bottom of body tag.

### CODE REVIEW

**Review by solodynamo — COMMENTED** [review]
CSS should never be declared on bottom in body, just to resolve a warning we should not take this step.

**Comment by codyogden** [comment]
@solodynamo I agree that the tag should be in the `head`, but should we inline critical CSS to resolve this warning, then follow the deferred styling suggested by Google?

**Comment by solodynamo** [comment]
Yes , as at current we have less css so we may consider inlining some part of css to boost critical rendering.

**Comment by LukeSchlangen** [comment]
Thank you guys! I'll remove that issue!

**Pull request closed without merging**
