### PR TITLE
modifications in fonts and styles

### PR DESCRIPTION
**Pull request by aditya2000**

### CODE REVIEW

**Review by LukeSchlangen — APPROVED** [review]
Love it! Thank you for contributing!

**Comment by aditya2000** [comment]
Thanks for merging it. By the way it was my first pull request. I'm really
excited about it 😃

**Comment by aditya2000** [comment]
If you need some more help. Please do ask me. I'll try to do my best

**Comment by LukeSchlangen** [comment]
That's great! I'd love to have you try adding an interview question to this project. It requires adding HTML to a couple different locations (adding links to connect it all together), but any [approachable-io](https://github.com/approachable-io) project is a great one to practice on if you want to keep contributing to open source!

**Pull request merged**
